version: '2'
services:

  # The backend
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - "APP_TEST=test"      
    ports:
      - "8080:8080"
    links:
      - redis
      - database
  # The Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always      
  # The Database
  database:
    image: mysql:5.6
    container_name: database
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"
  #phpmyadmin        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8082:80
    links:
      - database:db
volumes:
  dbdata: