version: '3.1'
services:

  # The backend
  backend:
    container_name: backend
    build:
      context: server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    environment:
      - "ENV=DEV"
      - "APP_TEST=test"
    ports:
      - "8080:8080"
    links:
      - database

  # The Database
  database:
    image: mysql:5.6
    container_name: database
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=todos"
      - "MYSQL_USER=todos"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8082:80
    links:
      - database:db
volumes:
  dbdata:
